In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset.head()
dataset = dataset.astype(int)

In [6]:
dataset.head()

   age  bmi  children  charges  sex_male  smoker_yes
0   19   27         0    16884         0           1
1   18   33         1     1725         1           0
2   28   33         3     4449         1           0
3   33   22         0    21984         1           0
4   32   28         0     3866         1           0

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [8]:
indep = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dept = dataset[['charges']]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(indep,dept,test_size=0.20,random_state=42)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
param_grid = { 'criterion':['absolute_error','squared_error','friedman_mse','poisson'],'max_features':[None,'sqrt','log2'],'splitter':['best','random']}
grid  = GridSearchCV(DecisionTreeRegressor(),param_grid, refit = True, verbose=3,n_jobs=-1)

grid.fit(indep,dept)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

In [ ]:
re = grid.cv_results_

#grid_predictions = grid.predict(X_test)
print('The R_score value for best parameter{}:'.format(grid.best_params_))

In [ ]:
table = pd.DataFrame.from_dict(re)

In [ ]:
table

In [ ]:
age_input = float(input('Age:'))
bmi_input  = float(input('BMI:'))
Children_input = int(input('Children:'))
sex_male_input=int(input('Sex Male 0 or 1:'))
smoker_yes_input=int(input('smoker yes 0 or 1:'))

In [ ]:
Future_prediction =grid.predict([[age_input,bmi_input,Children_input,sex_male_input,smoker_yes_input]])
print("Future_prediction={}".format(Future_prediction))

####