In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

# Convert categorical data to numerical
from sklearn.preprocessing import LabelEncoder

# Example dataset
data = {'Smoker': ['Yes', 'No', 'Yes', 'No', 'Yes']}
df = pd.DataFrame(data)

# Create label encoder object
le = LabelEncoder()

# Fit and transform the 'Smoker' column
df['Smoker'] = le.fit_transform(df['Smoker'])

print(df)

In [7]:
dataset = pd.get_dummies(dataset)
dataset = dataset.astype(int)

In [9]:
dataset.head()

   age  bmi  children  charges  sex_female  sex_male  smoker_no  smoker_yes
0   19   27         0    16884           1         0          0           1
1   18   33         1     1725           0         1          1           0
2   28   33         3     4449           0         1          1           0
3   33   22         0    21984           0         1          1           0
4   32   28         0     3866           0         1          1           0

In [11]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='object')

In [14]:
Independent = dataset[['age', 'bmi', 'children','sex_female', 'sex_male',
       'smoker_no', 'smoker_yes']]
Dependent = dataset[['charges']]

In [15]:
Independent.head()

   age  bmi  children  sex_female  sex_male  smoker_no  smoker_yes
0   19   27         0           1         0          0           1
1   18   33         1           0         1          1           0
2   28   33         3           0         1          1           0
3   33   22         0           0         1          1           0
4   32   28         0           0         1          1           0

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(Independent,Dependent,test_size = 0.30,random_state = 42)

In [79]:
# Linear regression

from sklearn.linear_model import LinearRegression
regressor1 = LinearRegression()
regressor1 = regressor1.fit(X_train,y_train)

In [80]:
y_pred = regressor1.predict(X_test)

In [81]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)

In [82]:
r_score

0.7681647919672667

In [83]:
# SVR Regression

from sklearn.svm import SVR
regressor2 = SVR(kernel='sigmoid', C =5000)
regressor2 = regressor2.fit(X_train,y_train)
y_pred = regressor2.predict(X_test)
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)
r_score

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-23.586756248926093

In [84]:
# Decision Tree Regression

from sklearn.tree import DecisionTreeRegressor

regressor3 = DecisionTreeRegressor(criterion='poisson',splitter='best', max_features=None, random_state=0)
regressor3 = regressor3.fit(X_train,y_train)
y_pred = regressor3.predict(X_test)
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)
r_score

0.7685195385899634

In [141]:
from sklearn.ensemble import RandomForestRegressor

regressor4 = RandomForestRegressor(n_estimators=100,criterion='poisson',random_state=42,max_features=None)
regressor4 = regressor4.fit(X_train,y_train)
y_pred = regressor4.predict(X_test)
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)
r_score

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.841216778726616