In [1]:
#import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
dataset = pd.get_dummies(dataset,drop_first = True)
dataset=dataset.astype(int)

In [5]:
dataset.head()

    User ID  Age  EstimatedSalary  Purchased  Gender_Male
0  15624510   19            19000          0            1
1  15810944   35            20000          0            1
2  15668575   26            43000          0            0
3  15603246   27            57000          0            0
4  15804002   19            76000          0            1

In [6]:
dataset = dataset.drop('User ID',axis=1)

In [7]:
dataset.head()

   Age  EstimatedSalary  Purchased  Gender_Male
0   19            19000          0            1
1   35            20000          0            1
2   26            43000          0            0
3   27            57000          0            0
4   19            76000          0            1

In [8]:
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [9]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [10]:
ind = dataset[['Age', 'EstimatedSalary', 'Gender_Male']]
dep = dataset[['Purchased']]

In [11]:
ind.shape

(400, 3)

In [12]:
#split train,test,split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(ind,dep,test_size=1/3,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV



param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid_clas=grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
11 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.82518593 0.84039574 0.81690115 0.86030705
        nan        nan 0.8149359  0.87240409 0.80796456 0.8597995 ]
  warnings.warn(
C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [18]:
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)

In [ ]:
print(re)

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,grid_predictions)
print(cm)

[[79  6]
 [ 4 45]]

confusion matrix:

1.Accuracy - What is the % of correctly classified purchase yes and no from the total test data?
TP+TN/TP+TN+FP+FN = 79+45/79+6+4+45 = 124/134 = 0.9253

2.Recall - Purchase_yes(what is the % of correctly classified purchase yes from the total purchased yes from test data?)
TP/TP+FN = 79/79+6 = 0.9294

Purchase_no(what is the % of correctly classified purchase No from the total purchased no from test data?)
TN/TN+FP = 45/45+4 = 0.9183

3.Precision - Purchase_yes(what is the % of correctly classified purchase yes to sum of  correctly classified purchase yes and wrongly classified purchased yes from test data?)
TP/TP+FP = 79/79+4 = 79/83 = 0.9518

Purchase_No(what is the % of correctly classified purchase No to sum of  correctly classified purchase No and wrongly classified purchased No from test data?)
TN/TN+FN = 45/45+6 =0.8823

4. F1 Score - Purchase_yes(What is overall performance of Purchase_yes?)
2(precisionYes*RecallYes)/precisionYes+RecallYes = 2(0.95*0.93)/0.95+0.93 = 1.767/1.88 = 0.9398

Purchase_No(What is overall performance of Purchase No?)
2(precisionNo*RecallNo)/precisionNo+RecallNo = 2(0.91*0.88)/0.91+0.88 = 1.6016/1.79 = 0.8947

5. Macro Average:
Precision - What is average performance of precision correctly and wrongly classified Purchase_yes and Purchase_No?
Precision(yes)+Precision(No)/2 = 0.95+0.88/2 = 0.92

Recall - What is average performance of Recall correctly and wrongly classified Purchase_yes and Purchase_No?
Recall(yes)+Recall(No)/2 = 0.93+0.92/2 = 0.925

F1 Score - What is average performance of F1 Score correctly and wrongly classified Purchase_yes and Purchase_No?
F1 Score(yes)+F1 Score(No)/2 = 0.9398+0.8947/2 = 1.8345/2 = 0.91725

6. Weighted Average:
Precision - What is sum of product of proportion rate of each class Purchase_yes and Purchase_No?
Precision(yes)*(85/134)+Precision(No)*(49/134) = 0.95*85/134+0.88*49/134 = 0.60+0.32 = 0.92

Recall - What is sum of product of proportion rate of each class Purchase_yes and Purchase_No?
Recall(yes)*(85/134)+Recall(No)*(49/134) = 0.5895+0.3357 = 0.925

F1 Score - What is sum of product of proportion rate of each class Purchase_yes and Purchase_No?
F1 Score(yes)*(85/134)*(85/134)+F1 Score(No)*(49/134) = 0.596+0.327 = 0.923

In [20]:
from sklearn.metrics import classification_report
clr = classification_report(y_test,grid_predictions)
print(clr )

              precision    recall  f1-score   support

           0       0.95      0.93      0.94        85
           1       0.88      0.92      0.90        49

    accuracy                           0.93       134
   macro avg       0.92      0.92      0.92       134
weighted avg       0.93      0.93      0.93       134

In [21]:
import pickle
filename = 'Finalize_Model_RF.sav'
pickle.dump(grid_clas,open(filename, 'wb'))
pickle.dump(sc, open("Scaler_RF.sav", 'wb'))

In [22]:
age = int(input('Enter age:'))
print(age)
salary = float(input('Enter salary:'))
print(salary)
sex_male = int(input('Enter sex_male:'))
print(sex_male)
preinput= sc.transform([[age, salary, sex_male ]])

Enter age: 50

50

Enter salary: 200000

200000.0

Enter sex_male: 1

1

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [23]:
loaded_model = pickle.load(open('Finalize_Model_RF.sav', 'rb'))

age = int(input('Enter age:'))
print(age)
salary = float(input('Enter salary:'))
print(salary)
sex_male = int(input('Enter sex_male:'))
print(sex_male)

In [24]:
result =loaded_model.predict(preinput)

In [25]:
print(result)

[1]

In [ ]:
dataset.columns

#####